apiVersion: v1
kind: ConfigMap
metadata:
  name: oraclexe-configmap
data:
  # property-like keys; each key maps to a simple value
  # oracle_password: "manager12"
  app_user: "vaja"
  # app_user_password: "vaja123"

---

apiVersion: v1
kind: Secret
metadata:
  name: oraclexe-secret
type: Opaque
data:
  app_user_password: dmFqYTEyMw==
  oracle_password: bWFuYWdlcjEy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclexe-deployment
  labels:
    db: oraclexe
spec:
  selector:
    matchLabels:
      db: oraclexe
  replicas: 1
  template:
    metadata:
      labels:
        db: oraclexe
    spec:
      containers:
        - name: oraclexe
          image: gvenzl/oracle-xe
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oraclexe-secret
                  key: oracle_password
            - name: APP_USER
              valueFrom:
                configMapKeyRef:
                  name: oraclexe-configmap
                  key: app_user
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oraclexe-secret
                  key: app_user_password
          volumeMounts:
            - mountPath: "/opt/oracle/oradata"
              name: oraclexe-pv-storage
      volumes:
        - name: oraclexe-pv-storage
          persistentVolumeClaim:
            claimName: oraclexe-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oraclexe
spec:
  type: LoadBalancer
  selector:
    db: oraclexe
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-configmap
data:
  parameter: "D"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deployment
  labels:
    app: microservice-web
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: microservice-web
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-web
    spec:
      containers:
        - name: microservice-web
          image: corkovic/microservice-web:latest
          ports:
            - containerPort: 9080
          env:
            - name: valueFromKubernetesConfigMap
              valueFrom:
                configMapKeyRef:
                  name: ms-configmap
                  key: parameter
          # system probes
          readinessProbe:
            httpGet:
              host:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              host:
              path: /health/live
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ms-service
  labels:
    app: microservice-web
spec:
  type: LoadBalancer
  selector:
    app: microservice-web
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
