apiVersion: v1
kind: ConfigMap
metadata:
  name: oraclexe-configmap
  namespace: default
data:
  # property-like keys; each key maps to a simple value
  # oracle_password: "manager12"
  app_user: "vaja"
  # app_user_password: "vaja123"
---
apiVersion: v1
kind: Secret
metadata:
  name: oraclexe-secret
  namespace: default
type: Opaque
data:
  app_user_password: dmFqYTEyMw==
  oracle_password: bWFuYWdlcjEy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclexe-deployment
  namespace: default
  labels:
    db: oraclexe
spec:
  selector:
    matchLabels:
      db: oraclexe
  replicas: 1
  template:
    metadata:
      labels:
        db: oraclexe
    spec:
      containers:
        - name: oraclexe
          image: gvenzl/oracle-xe
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oraclexe-secret
                  key: oracle_password
            - name: APP_USER
              valueFrom:
                configMapKeyRef:
                  name: oraclexe-configmap
                  key: app_user
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oraclexe-secret
                  key: app_user_password
          volumeMounts:
            - mountPath: "/opt/oracle/oradata"
              name: oraclexe-pv-storage
      volumes:
        - name: oraclexe-pv-storage
          persistentVolumeClaim:
            claimName: oraclexe-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oraclexe
  namespace: default
spec:
  type: LoadBalancer
  selector:
    db: oraclexe
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-configmap
data:
  parameter: "D"
  db_url: "jdbc:oracle:thin:@//oraclexe:1521/XEPDB1"
  db_username: "vaja"
---
apiVersion: v1
kind: Secret
metadata:
  name: microservice-web-secret
type: Opaque
data:
  db_password: dmFqYTEyMw==
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: microservice-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deployment
  namespace: default
  labels:
    app: microservice-web
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: microservice-web
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-web
    spec:
      containers:
        - name: microservice-web
          #image: microservice-web:latest
          image: corkovic/microservice-web:1.6n
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: valueFromKubernetesConfigMap
              valueFrom:
                configMapKeyRef:
                  name: ms-configmap
                  key: parameter
            - name: db_url
              valueFrom:
                configMapKeyRef:
                  name: ms-configmap
                  key: db_url
            - name: db_username
              valueFrom:
                configMapKeyRef:
                  name: ms-configmap
                  key: db_username
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: microservice-web-secret
                  key: db_password
          # system probes
          readinessProbe:
            httpGet:
              host:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              host:
              path: /health/live
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ms-service
  namespace: default
  labels:
    app: microservice-web
spec:
  type: LoadBalancer
  selector:
    app: microservice-web
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
