apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deployment
  namespace: test
  labels:
    app: microservice-web
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: microservice-web
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-web
    spec:
      containers:
        - name: microservice-web
          image: corkovic/microservice-web:latest
          ports:
            - containerPort: 9080
          env:
            - name: valueFromKubernetesConfigMap
              valueFrom:
                configMapKeyRef:
                  name: ms-configmap
                  key: parameter
          # system probes
          readinessProbe:
            httpGet:
              host:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              host:
              path: /health/live
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
